HDFC_PRODUCT_CATALOGUE = [
    # ── ACCOUNTS ──
    {
        "name": "Regular Savings Account",
        "category": "accounts",
        "subcategory": "savings",
        "description": "Standard savings account with basic banking features",
        "features": ["Debit Card", "NetBanking", "Mobile Banking", "SMS Alerts", "NEFT/RTGS/IMPS"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 3.0,
        "benefits": ["Free debit card", "Basic banking", "Interest on savings"],
        "tags": ["basic", "savings", "everyone"],
    },
    {
        "name": "Savings Max Account",
        "category": "accounts",
        "subcategory": "savings",
        "description": "Premium savings account with higher interest and benefits",
        "features": ["Higher Interest", "Free Cheque Book", "Free NEFT/RTGS", "Priority Banking", "Free IMPS"],
        "eligibility_criteria": {"min_age": 18, "min_income": 500000},
        "min_income": 500000,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 4.0,
        "benefits": ["Higher interest", "Free cheque book", "Priority service"],
        "tags": ["premium", "savings", "high-balance"],
    },
    {
        "name": "Senior Citizen Savings Account",
        "category": "accounts",
        "subcategory": "savings",
        "description": "Special savings account for senior citizens with extra benefits",
        "features": ["Higher Interest", "Free Doorstep Banking", "Health Benefits", "Free DD"],
        "eligibility_criteria": {"min_age": 60, "min_income": 0},
        "min_income": 0,
        "min_age": 60,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["retired", "all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 5.0,
        "benefits": ["Extra interest", "Doorstep banking", "Health cover"],
        "tags": ["senior", "savings", "retired"],
    },
    {
        "name": "Kids Advantage Account",
        "category": "accounts",
        "subcategory": "savings",
        "description": "Savings account for children with education benefits",
        "features": ["Education Benefits", "Free Debit Card", "Online Safety", "Gift Features"],
        "eligibility_criteria": {"min_age": 0, "max_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 0,
        "max_age": 18,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["student"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 4.0,
        "benefits": ["Education perks", "Parental controls", "Gift features"],
        "tags": ["kids", "education", "savings"],
    },
    {
        "name": "Women's Savings Account",
        "category": "accounts",
        "subcategory": "savings",
        "description": "Tailored savings account for women with exclusive benefits",
        "features": ["Higher Interest", "Free Insurance", "Health Benefits", "Shopping Rewards"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0, "gender": "female"},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 3.5,
        "benefits": ["Extra interest", "Free insurance", "Shopping rewards"],
        "tags": ["women", "savings", "exclusive"],
    },
    {
        "name": "Salary Account",
        "category": "accounts",
        "subcategory": "salary",
        "description": "Zero balance salary account with premium benefits",
        "features": ["Zero Balance", "Free Salary Processing", "Free ATM", "Overdraft Facility"],
        "eligibility_criteria": {"min_age": 18, "min_income": 25000},
        "min_income": 25000,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["government", "private"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 3.5,
        "benefits": ["Zero balance", "Free ATM", "Overdraft"],
        "tags": ["salary", "zero-balance", "employed"],
    },
    {
        "name": "Current Account",
        "category": "accounts",
        "subcategory": "current",
        "description": "Business current account with high transaction limits",
        "features": ["Unlimited Transactions", "High Cash Deposit", "Business Features", "OD Facility"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "moderate",
        "occupation_types": ["business", "self_employed", "professional"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 5000,
        "interest_rate": 0,
        "benefits": ["Unlimited transactions", "High deposit limits", "Business tools"],
        "tags": ["business", "current", "transactions"],
    },

    # ── CREDIT CARDS ──
    {
        "name": "Millennia Credit Card",
        "category": "credit_cards",
        "subcategory": "standard",
        "description": "Entry-level credit card for the digital-first generation",
        "features": ["5% Cashback on Amazon", "1% on all spends", "Fuel Surcharge Waiver", "Contactless"],
        "eligibility_criteria": {"min_age": 21, "min_income": 300000, "min_credit_score": 650},
        "min_income": 300000,
        "min_age": 21,
        "max_age": 65,
        "min_credit_score": 650,
        "risk_profile": "moderate",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 1000,
        "interest_rate": 3.49,
        "benefits": ["5% on Amazon", "Contactless", "Fuel waiver"],
        "tags": ["entry", "digital", "cashback"],
    },
    {
        "name": "Regalia Gold Credit Card",
        "category": "credit_cards",
        "subcategory": "premium",
        "description": "Premium travel and lifestyle credit card",
        "features": ["Airport Lounge Access", "6 Reward Points/150", "Travel Insurance", "Golf Access"],
        "eligibility_criteria": {"min_age": 21, "min_income": 1200000, "min_credit_score": 700},
        "min_income": 1200000,
        "min_age": 21,
        "max_age": 65,
        "min_credit_score": 700,
        "risk_profile": "moderate",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": True,
        "annual_fee": 5000,
        "interest_rate": 3.49,
        "benefits": ["Airport lounge", "Travel insurance", "Golf access", "Reward points"],
        "tags": ["premium", "travel", "lounge", "gold"],
    },
    {
        "name": "Infinia Credit Card",
        "category": "credit_cards",
        "subcategory": "super-premium",
        "description": "Ultra-premium metal credit card for elite customers",
        "features": ["Unlimited Lounge", "10 Reward Points/150", "Concierge", "Golf", "Miles Transfer"],
        "eligibility_criteria": {"min_age": 21, "min_income": 3000000, "min_credit_score": 750},
        "min_income": 3000000,
        "min_age": 21,
        "max_age": 65,
        "min_credit_score": 750,
        "risk_profile": "aggressive",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": True,
        "annual_fee": 12500,
        "interest_rate": 3.49,
        "benefits": ["Unlimited lounge", "Concierge", "Metal card", "Miles transfer"],
        "tags": ["elite", "metal", "ultra-premium", "infinia"],
    },
    {
        "name": "Diners Club Black",
        "category": "credit_cards",
        "subcategory": "super-premium",
        "description": "Premium lifestyle card with exclusive dining and travel benefits",
        "features": ["Dining Privileges", "Unlimited Lounge", "Golf", "Concierge", "Spa"],
        "eligibility_criteria": {"min_age": 21, "min_income": 3000000, "min_credit_score": 750},
        "min_income": 3000000,
        "min_age": 21,
        "max_age": 65,
        "min_credit_score": 750,
        "risk_profile": "aggressive",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": True,
        "annual_fee": 15000,
        "interest_rate": 3.49,
        "benefits": ["Dining privileges", "Unlimited lounge", "Spa access"],
        "tags": ["elite", "dining", "travel", "black"],
    },
    {
        "name": "MoneyBack+ Credit Card",
        "category": "credit_cards",
        "subcategory": "cashback",
        "description": "Cashback focused credit card for everyday spends",
        "features": ["10% Cashback on Utility", "5% on Shopping", "Fuel Surcharge Waiver"],
        "eligibility_criteria": {"min_age": 21, "min_income": 300000, "min_credit_score": 650},
        "min_income": 300000,
        "min_age": 21,
        "max_age": 65,
        "min_credit_score": 650,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 500,
        "interest_rate": 3.49,
        "benefits": ["10% on utility", "5% on shopping", "Fuel waiver"],
        "tags": ["cashback", "utility", "everyday"],
    },
    {
        "name": "IndianOil Credit Card",
        "category": "credit_cards",
        "subcategory": "fuel",
        "description": "Fuel rewards credit card for regular commuters",
        "features": ["5% on Fuel", "2.5% on Grocery", "1% on All Spends", "Fuel Surcharge Waiver"],
        "eligibility_criteria": {"min_age": 21, "min_income": 300000, "min_credit_score": 650},
        "min_income": 300000,
        "min_age": 21,
        "max_age": 65,
        "min_credit_score": 650,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 500,
        "interest_rate": 3.49,
        "benefits": ["5% on fuel", "2.5% on grocery", "Fuel waiver"],
        "tags": ["fuel", "commute", "indianoil"],
    },
    {
        "name": "Tata Neu Infinity Credit Card",
        "category": "credit_cards",
        "subcategory": "co-brand",
        "description": "Co-brand card with Tata ecosystem benefits",
        "features": ["5 NeuCoins/150", "Airport Lounge", "Tata Brand Discounts", "Welcome Voucher"],
        "eligibility_criteria": {"min_age": 21, "min_income": 600000, "min_credit_score": 700},
        "min_income": 600000,
        "min_age": 21,
        "max_age": 65,
        "min_credit_score": 700,
        "risk_profile": "moderate",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 1500,
        "interest_rate": 3.49,
        "benefits": ["NeuCoins", "Tata discounts", "Lounge access"],
        "tags": ["tata", "co-brand", "neu"],
    },
    {
        "name": "Swiggy HDFC Card",
        "category": "credit_cards",
        "subcategory": "co-brand",
        "description": "Food and delivery focused credit card",
        "features": ["10% on Swiggy", "5% on Food Delivery", "Free Delivery", "Movie Benefits"],
        "eligibility_criteria": {"min_age": 21, "min_income": 300000, "min_credit_score": 650},
        "min_income": 300000,
        "min_age": 21,
        "max_age": 65,
        "min_credit_score": 650,
        "risk_profile": "moderate",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 500,
        "interest_rate": 3.49,
        "benefits": ["10% on Swiggy", "Free delivery", "Movie deals"],
        "tags": ["food", "swiggy", "delivery"],
    },
    {
        "name": "Marriott Bonvoy Card",
        "category": "credit_cards",
        "subcategory": "travel",
        "description": "Hotel rewards credit card for travel enthusiasts",
        "features": ["Free Night Voucher", "Marriott Points", "Lounge Access", "Room Upgrade"],
        "eligibility_criteria": {"min_age": 21, "min_income": 1500000, "min_credit_score": 700},
        "min_income": 1500000,
        "min_age": 21,
        "max_age": 65,
        "min_credit_score": 700,
        "risk_profile": "moderate",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": True,
        "annual_fee": 3000,
        "interest_rate": 3.49,
        "benefits": ["Free night", "Marriott points", "Room upgrade"],
        "tags": ["hotel", "travel", "marriott", "bonvoy"],
    },
    {
        "name": "Business MoneyBack",
        "category": "credit_cards",
        "subcategory": "business",
        "description": "Credit card for business expenses with cashback",
        "features": ["5% on Business Spends", "2x Rewards on GST", "Fuel Surcharge Waiver"],
        "eligibility_criteria": {"min_age": 25, "min_income": 600000, "min_credit_score": 700},
        "min_income": 600000,
        "min_age": 25,
        "max_age": 65,
        "min_credit_score": 700,
        "risk_profile": "moderate",
        "occupation_types": ["business", "self_employed"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 1000,
        "interest_rate": 3.49,
        "benefits": ["5% on business", "GST rewards", "Fuel waiver"],
        "tags": ["business", "cashback", "corporate"],
    },
    {
        "name": "BizGrow Credit Card",
        "category": "credit_cards",
        "subcategory": "business",
        "description": "Business growth card for SMEs",
        "features": ["High Credit Limit", "Business Rewards", "Expense Management", "GST Benefits"],
        "eligibility_criteria": {"min_age": 25, "min_income": 1000000, "min_credit_score": 700},
        "min_income": 1000000,
        "min_age": 25,
        "max_age": 65,
        "min_credit_score": 700,
        "risk_profile": "moderate",
        "occupation_types": ["business", "self_employed"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 1500,
        "interest_rate": 3.49,
        "benefits": ["High limit", "Business rewards", "Expense tools"],
        "tags": ["business", "sme", "growth"],
    },

    # ── LOANS ──
    {
        "name": "Personal Loan",
        "category": "loans",
        "subcategory": "personal",
        "description": "Unsecured personal loan for various needs",
        "features": ["No Collateral", "Quick Disbursal", "Flexible Tenure", "Online Apply"],
        "eligibility_criteria": {"min_age": 23, "min_income": 300000, "min_credit_score": 650},
        "min_income": 300000,
        "min_age": 23,
        "max_age": 60,
        "min_credit_score": 650,
        "risk_profile": "moderate",
        "occupation_types": ["government", "private", "professional", "self_employed"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 10.5,
        "processing_fee": 2.5,
        "benefits": ["No collateral", "Quick approval", "Flexible EMI"],
        "tags": ["personal", "unsecured", "quick"],
    },
    {
        "name": "Home Loan",
        "category": "loans",
        "subcategory": "home",
        "description": "Home loan with competitive interest rates",
        "features": ["Low Interest", "Long Tenure", "Balance Transfer", "Top-up Loan", "Tax Benefits"],
        "eligibility_criteria": {"min_age": 23, "min_income": 500000, "min_credit_score": 650},
        "min_income": 500000,
        "min_age": 23,
        "max_age": 65,
        "min_credit_score": 650,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 8.5,
        "processing_fee": 0.5,
        "benefits": ["Low interest", "Tax benefits", "Long tenure"],
        "tags": ["home", "housing", "mortgage"],
    },
    {
        "name": "Car Loan",
        "category": "loans",
        "subcategory": "auto",
        "description": "New and used car loan with attractive rates",
        "features": ["Up to 100% Financing", "Long Tenure", "Quick Approval", "Pre-approved Offers"],
        "eligibility_criteria": {"min_age": 21, "min_income": 300000, "min_credit_score": 650},
        "min_income": 300000,
        "min_age": 21,
        "max_age": 65,
        "min_credit_score": 650,
        "risk_profile": "moderate",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 8.75,
        "processing_fee": 1,
        "benefits": ["100% financing", "Long tenure", "Quick approval"],
        "tags": ["car", "auto", "vehicle"],
    },
    {
        "name": "Gold Loan",
        "category": "loans",
        "subcategory": "gold",
        "description": "Quick loan against gold jewellery",
        "features": ["Instant Disbursal", "No Income Proof", "Low Interest", "Flexible Repayment"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0, "min_credit_score": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 7.0,
        "processing_fee": 0,
        "benefits": ["Instant cash", "No income proof", "Low rate"],
        "tags": ["gold", "quick", "secured"],
    },
    {
        "name": "Education Loan",
        "category": "loans",
        "subcategory": "education",
        "description": "Education loan for higher studies in India and abroad",
        "features": ["Covers Tuition", "Living Expenses", "Moratorium Period", "Tax Benefits"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0, "min_credit_score": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 35,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["student"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 8.5,
        "processing_fee": 0,
        "benefits": ["Covers all expenses", "Moratorium period", "Tax benefits"],
        "tags": ["education", "study", "student"],
    },
    {
        "name": "Loan Against Property",
        "category": "loans",
        "subcategory": "secured",
        "description": "Secured loan against residential or commercial property",
        "features": ["High Loan Amount", "Long Tenure", "Lower Interest", "Flexible Use"],
        "eligibility_criteria": {"min_age": 25, "min_income": 500000, "min_credit_score": 650},
        "min_income": 500000,
        "min_age": 25,
        "max_age": 65,
        "min_credit_score": 650,
        "risk_profile": "moderate",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 8.75,
        "processing_fee": 1,
        "benefits": ["High amount", "Low interest", "Flexible use"],
        "tags": ["property", "secured", "high-value"],
    },
    {
        "name": "Business Loan",
        "category": "loans",
        "subcategory": "business",
        "description": "Term loan for business expansion and working capital",
        "features": ["Up to 50 Lakh", "Quick Processing", "Minimal Documentation", "Prepayment"],
        "eligibility_criteria": {"min_age": 25, "min_income": 1000000, "min_credit_score": 700},
        "min_income": 1000000,
        "min_age": 25,
        "max_age": 65,
        "min_credit_score": 700,
        "risk_profile": "moderate",
        "occupation_types": ["business", "self_employed"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 11.0,
        "processing_fee": 2,
        "benefits": ["High amount", "Quick processing", "Flexible repayment"],
        "tags": ["business", "enterprise", "expansion"],
    },
    {
        "name": "MSME Loan",
        "category": "loans",
        "subcategory": "msme",
        "description": "Loan for micro, small and medium enterprises",
        "features": ["Government Subsidy", "Quick Approval", "Low Interest", "Flexible Repayment"],
        "eligibility_criteria": {"min_age": 25, "min_income": 500000, "min_credit_score": 650},
        "min_income": 500000,
        "min_age": 25,
        "max_age": 65,
        "min_credit_score": 650,
        "risk_profile": "moderate",
        "occupation_types": ["business", "self_employed"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 9.5,
        "processing_fee": 1,
        "benefits": ["Govt subsidy", "Quick approval", "Low rate"],
        "tags": ["msme", "small-business", "sme"],
    },
    {
        "name": "Working Capital Loan",
        "category": "loans",
        "subcategory": "business",
        "description": "Overdraft facility for business working capital needs",
        "features": ["Overdraft Facility", "Pay Interest on Usage", "Revolving Credit", "Flexibility"],
        "eligibility_criteria": {"min_age": 25, "min_income": 1000000, "min_credit_score": 700},
        "min_income": 1000000,
        "min_age": 25,
        "max_age": 65,
        "min_credit_score": 700,
        "risk_profile": "moderate",
        "occupation_types": ["business", "self_employed"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 10.0,
        "processing_fee": 1,
        "benefits": ["OD facility", "Pay on usage", "Revolving credit"],
        "tags": ["working-capital", "od", "business"],
    },
    {
        "name": "Commercial Vehicle Loan",
        "category": "loans",
        "subcategory": "auto",
        "description": "Loan for commercial vehicles and fleet",
        "features": ["Up to 90% Financing", "Long Tenure", "Fleet Management", "Insurance"],
        "eligibility_criteria": {"min_age": 23, "min_income": 500000, "min_credit_score": 650},
        "min_income": 500000,
        "min_age": 23,
        "max_age": 65,
        "min_credit_score": 650,
        "risk_profile": "moderate",
        "occupation_types": ["business", "self_employed"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 9.0,
        "processing_fee": 1,
        "benefits": ["90% financing", "Long tenure", "Fleet tools"],
        "tags": ["commercial", "vehicle", "fleet"],
    },
    {
        "name": "Two Wheeler Loan",
        "category": "loans",
        "subcategory": "auto",
        "description": "Loan for two wheelers with quick approval",
        "features": ["Up to 95% Financing", "Low EMI", "Quick Approval", "Insurance"],
        "eligibility_criteria": {"min_age": 18, "min_income": 150000, "min_credit_score": 600},
        "min_income": 150000,
        "min_age": 18,
        "max_age": 65,
        "min_credit_score": 600,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 8.5,
        "processing_fee": 0,
        "benefits": ["95% financing", "Low EMI", "Quick approval"],
        "tags": ["two-wheeler", "bike", "scooter"],
    },

    # ── INVESTMENTS ──
    {
        "name": "Fixed Deposit",
        "category": "investments",
        "subcategory": "fd",
        "description": "Guaranteed returns with flexible tenure options",
        "features": ["Guaranteed Returns", "Flexible Tenure", "Loan Against FD", "Auto-Renewal"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 6.5,
        "benefits": ["Guaranteed returns", "Safe investment", "Loan facility"],
        "tags": ["fd", "fixed-deposit", "safe", "guaranteed"],
    },
    {
        "name": "Recurring Deposit",
        "category": "investments",
        "subcategory": "rd",
        "description": "Systematic savings with monthly installments",
        "features": ["Monthly Savings", "Guaranteed Returns", "Flexible Amount", "Auto-Debit"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 6.0,
        "benefits": ["Systematic savings", "Guaranteed returns", "Flexible"],
        "tags": ["rd", "recurring", "systematic"],
    },
    {
        "name": "Systematic Investment Plan (SIP)",
        "category": "investments",
        "subcategory": "mutual_fund",
        "description": "Regular investment in mutual funds for wealth creation",
        "features": ["Rupee Cost Averaging", "Power of Compounding", "Flexible Amount", "Goal Planning"],
        "eligibility_criteria": {"min_age": 18, "min_income": 100000},
        "min_income": 100000,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "moderate",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 12.0,
        "benefits": ["Wealth creation", "Diversification", "Tax benefits"],
        "tags": ["sip", "mutual-fund", "investment", "wealth"],
    },
    {
        "name": "Mutual Funds",
        "category": "investments",
        "subcategory": "mutual_fund",
        "description": "Direct mutual fund investments across categories",
        "features": ["Multiple Categories", "Professional Management", "Liquidity", "Diversification"],
        "eligibility_criteria": {"min_age": 18, "min_income": 100000},
        "min_income": 100000,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "moderate",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 12.0,
        "benefits": ["Diversification", "Expert management", "Tax savings"],
        "tags": ["mutual-fund", "investment", "equity"],
    },
    {
        "name": "Demat Account",
        "category": "investments",
        "subcategory": "trading",
        "description": "Demat account for equity and derivatives trading",
        "features": ["IPO Access", "Trading", "ETF", "Bond Trading", "SGB"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "aggressive",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 0,
        "benefits": ["IPO access", "Trading platform", "Multiple instruments"],
        "tags": ["demat", "trading", "equity", "stocks"],
    },
    {
        "name": "NPS (National Pension System)",
        "category": "investments",
        "subcategory": "pension",
        "description": "Government pension scheme for retirement planning",
        "features": ["Tax Benefits", "Long-term Growth", "Low Cost", "Regulated", "80C Deduction"],
        "eligibility_criteria": {"min_age": 18, "max_age": 65, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 65,
        "min_credit_score": 0,
        "risk_profile": "moderate",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 10.0,
        "benefits": ["Tax benefits", "Retirement corpus", "Low cost"],
        "tags": ["nps", "pension", "retirement", "80c"],
    },

    # ── INSURANCE ──
    {
        "name": "HDFC Life Insurance",
        "category": "insurance",
        "subcategory": "life",
        "description": "Term and whole life insurance plans",
        "features": ["Life Cover", "Tax Benefits", "Critical Illness", "Accidental Cover", "Maturity Benefit"],
        "eligibility_criteria": {"min_age": 18, "max_age": 65, "min_income": 300000},
        "min_income": 300000,
        "min_age": 18,
        "max_age": 65,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 0,
        "benefits": ["Life protection", "Tax savings", "Family security"],
        "tags": ["life", "insurance", "protection", "term"],
    },
    {
        "name": "HDFC Health Insurance",
        "category": "insurance",
        "subcategory": "health",
        "description": "Comprehensive health insurance plans",
        "features": ["Cashless Hospitalization", "Pre/Post Hospital", "Day Care", "Restoration", "No Claim Bonus"],
        "eligibility_criteria": {"min_age": 5, "max_age": 65, "min_income": 200000},
        "min_income": 200000,
        "min_age": 5,
        "max_age": 65,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 0,
        "benefits": ["Cashless treatment", "Health protection", "No claim bonus"],
        "tags": ["health", "insurance", "medical", "hospital"],
    },
    {
        "name": "HDFC Term Insurance",
        "category": "insurance",
        "subcategory": "term",
        "description": "Pure term life insurance at affordable premiums",
        "features": ["High Sum Assured", "Low Premium", "Critical Illness Rider", "Accidental Death"],
        "eligibility_criteria": {"min_age": 18, "max_age": 65, "min_income": 300000},
        "min_income": 300000,
        "min_age": 18,
        "max_age": 65,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 0,
        "benefits": ["High cover", "Low cost", "Family protection"],
        "tags": ["term", "insurance", "protection", "affordable"],
    },
    {
        "name": "HDFC Travel Insurance",
        "category": "insurance",
        "subcategory": "travel",
        "description": "Domestic and international travel insurance",
        "features": ["Trip Cancellation", "Medical Emergency", "Baggage Loss", "Flight Delay", "Emergency Evacuation"],
        "eligibility_criteria": {"min_age": 18, "max_age": 70, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 70,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 0,
        "benefits": ["Trip protection", "Medical cover", "Baggage cover"],
        "tags": ["travel", "insurance", "international", "trip"],
    },
    {
        "name": "HDFC Motor Insurance",
        "category": "insurance",
        "subcategory": "motor",
        "description": "Comprehensive motor insurance for cars and bikes",
        "features": ["Zero Depreciation", "Roadside Assistance", "Engine Protection", "NCB Protection"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 0,
        "benefits": ["Vehicle protection", "Roadside help", "No dep cover"],
        "tags": ["motor", "car", "bike", "vehicle-insurance"],
    },

    # ── DIGITAL PRODUCTS ──
    {
        "name": "FASTag",
        "category": "digital",
        "subcategory": "payments",
        "description": "Electronic toll collection tag",
        "features": ["Cashless Toll", "Fuel Payment", "Parking", "Online Recharge"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 200,
        "interest_rate": 0,
        "benefits": ["Cashless toll", "Fuel payment", "Easy recharge"],
        "tags": ["fastag", "toll", "digital", "payments"],
    },
    {
        "name": "PayZapp",
        "category": "digital",
        "subcategory": "payments",
        "description": "Digital wallet and payment app",
        "features": ["UPI Payments", "Bill Pay", "Recharge", "Shopping", "Money Transfer"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 0,
        "benefits": ["Easy payments", "Rewards", "Bill pay"],
        "tags": ["payzapp", "wallet", "upi", "digital"],
    },
    {
        "name": "Forex Card",
        "category": "digital",
        "subcategory": "travel",
        "description": "Multi-currency forex card for international travel",
        "features": ["Multi-Currency", "Locked Exchange Rate", "Global Acceptance", "Emergency Cash"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["all"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 300,
        "interest_rate": 0,
        "benefits": ["Multi-currency", "Best rates", "Global use"],
        "tags": ["forex", "travel", "international", "currency"],
    },
    {
        "name": "Merchant QR",
        "category": "digital",
        "subcategory": "payments",
        "description": "QR code based payment acceptance for merchants",
        "features": ["QR Payments", "Instant Settlement", "No Charges", "Dashboard", "Reports"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["business", "self_employed"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 0,
        "benefits": ["Accept payments", "Instant settlement", "Free setup"],
        "tags": ["merchant", "qr", "business", "payments"],
    },
    {
        "name": "POS Machine",
        "category": "digital",
        "subcategory": "payments",
        "description": "Point of Sale terminal for card acceptance",
        "features": ["Card Payment", "Tap & Pay", "EMI on POS", "Real-time Reports"],
        "eligibility_criteria": {"min_age": 18, "min_income": 0},
        "min_income": 0,
        "min_age": 18,
        "max_age": 100,
        "min_credit_score": 0,
        "risk_profile": "conservative",
        "occupation_types": ["business", "self_employed"],
        "is_active": True,
        "is_premium": False,
        "annual_fee": 0,
        "interest_rate": 0,
        "benefits": ["Accept all cards", "Tap & pay", "EMI facility"],
        "tags": ["pos", "terminal", "merchant", "cards"],
    },
]
